[package]
name = "simple"
version = "0.1.0"
authors = ["AMAGI <mail@amagi.dev>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
wasm-bindgen-test = "0.3.34"
retentive-lender = { path = "../.." }

[profile.release]
opt-level = "s"
