[package]
name = "retentive-lender"
version = "0.1.0"
edition = "2021"
authors = ["AMAGI <mail@amagi.dev>"]
description = "Dumb container for interior mutability with debug info, works on WebAssembly"
license = "MIT"
